name: Scraping

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/399324940941/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'esunhx@gorgias-case-study-491217.iam.gserviceaccount.com'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      
      - name: Install dependencies
        run: python3 -m pip install requirements.txt
      
      - name: Scaper
        run: python3 data/scraping.py